/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * Properties for ApiKeyTable construct.
 */
export interface ApiKeyTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table for platform API keys (Cognito-free auth for headless clients).
 *
 * Schema: key_id (PK) with one GSI for querying by owner.
 *
 * The presented key is `bgak_<key_id>_<secret>`; the authorizer parses key_id
 * and does a direct GetItem, so no secret-hash GSI is needed. Direct lookup by
 * partition key also avoids GSI eventual-consistency, so a revoked key stops
 * authenticating immediately.
 *
 * GSIs:
 * - UserIndex (PK: user_id, SK: created_at) — list API keys for a user.
 *   Projects only the attributes the list response needs; `key_hash` is
 *   deliberately excluded so the secret hash is never replicated into the index
 *   (defense-in-depth — the list path already strips it, this stops it being
 *   readable via the GSI at all).
 */
export class ApiKeyTable extends Construct {
  /**
   * GSI name for querying API keys by owner.
   * PK: user_id, SK: created_at.
   */
  public static readonly USER_INDEX = 'UserIndex';

  /**
   * The underlying DynamoDB table.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: ApiKeyTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'key_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: 'ttl',
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });

    this.table.addGlobalSecondaryIndex({
      indexName: ApiKeyTable.USER_INDEX,
      partitionKey: { name: 'user_id', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'created_at', type: dynamodb.AttributeType.STRING },
      // Everything the list response needs, minus `key_hash`. Key attributes
      // (key_id, user_id, created_at) are projected automatically.
      projectionType: dynamodb.ProjectionType.INCLUDE,
      nonKeyAttributes: ['name', 'status', 'scopes', 'updated_at', 'expires_at', 'revoked_at'],
    });
  }
}
