/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

// Hosted landing page for the Linear vault consent flow (RFC #249 Phase 1).
//
// WHY THIS EXISTS. The 3LO consent flow must be given a return URL, and after the
// user authorizes, AgentCore redirects the browser there with
// `?session_id=urn:ietf:params:oauth:request_uri:…`. The default flow points that
// at a localhost listener the CLI runs — which only works when the browser and the
// CLI are on the same machine. On a cloud desktop, an SSH box, or a container, the
// browser cannot reach the CLI's localhost, so consent dead-ends.
//
// This page is the substrate-independent alternative: consent lands on a URL that
// is reachable from anywhere, and the page shows the session id for the operator to
// paste back into `bgagent linear vault-setup <slug> --session <id>`.
//
// WHY IT IS STATIC (no Lambda). Finalizing a session requires
// CompleteResourceTokenAuth. Doing that here would mean a PUBLIC, unauthenticated
// endpoint that completes OAuth sessions on behalf of whoever calls it. Instead the
// page only DISPLAYS the id, and the CLI finalizes using the operator's own AWS
// credentials — the privileged step stays with a principal we can authorize.
import { RemovalPolicy } from 'aws-cdk-lib';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import { NagSuppressions } from 'cdk-nag';
import { Construct } from 'constructs';

export interface LinearVaultConsentPageProps {
  readonly removalPolicy?: RemovalPolicy;
  readonly autoDeleteObjects?: boolean;
}

/**
 * The consent landing page. `consentUrl` is what gets registered on the workload
 * identity's return-URL allowlist and passed as `resourceOauth2ReturnUrl`.
 */
export class LinearVaultConsentPage extends Construct {
  public readonly bucket: s3.Bucket;
  public readonly distribution: cloudfront.Distribution;

  /** `https://<dist>.cloudfront.net/` — the allowlisted return URL. */
  public readonly consentUrl: string;

  constructor(scope: Construct, id: string, props: LinearVaultConsentPageProps = {}) {
    super(scope, id);

    this.bucket = new s3.Bucket(this, 'Bucket', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
      autoDeleteObjects: props.autoDeleteObjects ?? true,
    });

    // CloudFront → S3 via Origin Access Control (same shape as ScreenshotBucket):
    // the bucket policy is generated by `withOriginAccessControl` and grants
    // GetObject to the distribution only, so account-level BPA stays satisfied.
    this.distribution = new cloudfront.Distribution(this, 'Distribution', {
      defaultRootObject: 'index.html',
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(this.bucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        allowedMethods: cloudfront.AllowedMethods.ALLOW_GET_HEAD,
        // The page must never be served from cache with a STALE query string
        // rendered into it. It renders `session_id` client-side from
        // window.location, so the HTML itself is identical for every visit and is
        // safe to cache — but the query string must not be part of the cache key
        // either, or every consent would be a cache miss for no benefit.
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
      },
      enableLogging: false,
      comment: 'ABCA Linear vault consent landing page',
    });

    new s3deploy.BucketDeployment(this, 'Page', {
      destinationBucket: this.bucket,
      // `Source.data` inlines the file at synth time — no Docker bundling.
      sources: [s3deploy.Source.data('index.html', renderConsentPage())],
      distribution: this.distribution,
      distributionPaths: ['/index.html'],
      prune: true,
    });

    this.consentUrl = `https://${this.distribution.distributionDomainName}/`;

    NagSuppressions.addResourceSuppressions(this.bucket, [
      {
        id: 'AwsSolutions-S1',
        reason:
          'Server access logs are not enabled. The bucket holds a single public, static HTML page with no user data — access logging would be pure volume for no security signal.',
      },
    ], true);

    NagSuppressions.addResourceSuppressions(this.distribution, [
      {
        id: 'AwsSolutions-CFR1',
        reason: 'No geo restriction: operators onboard workspaces from anywhere, and that is the whole point of a hosted consent page.',
      },
      {
        id: 'AwsSolutions-CFR2',
        reason: 'No WAF. The distribution serves one immutable static HTML page with no server-side logic, no auth, and no input handling — the session id is rendered client-side into textContent, never interpolated into markup.',
      },
      {
        id: 'AwsSolutions-CFR3',
        reason: 'Distribution access logs are not enabled — same rationale as the bucket (single static page, no user data).',
      },
      {
        id: 'AwsSolutions-CFR4',
        reason: 'Uses the default *.cloudfront.net certificate (TLSv1+ enforced by AWS); no custom domain, so no minimum-TLS-version override applies.',
      },
      {
        id: 'AwsSolutions-CFR7',
        reason: 'OAC is in use (`S3BucketOrigin.withOriginAccessControl`); cdk-nag misclassifies the L2 helper as an OAI deployment.',
      },
    ], true);

    // BucketDeployment synthesizes a CDK-managed Lambda + role we do not author.
    NagSuppressions.addResourceSuppressions(this, [
      {
        id: 'AwsSolutions-IAM4',
        reason: 'CDK BucketDeployment framework Lambda uses AWSLambdaBasicExecutionRole',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason: 'CDK BucketDeployment framework grants list/read/write on the destination bucket and its objects',
      },
      {
        id: 'AwsSolutions-L1',
        reason: 'CDK BucketDeployment framework manages its own Lambda runtime',
      },
    ], true);
  }
}

/**
 * The page itself. Deliberately self-contained: no external scripts, styles, or
 * fonts, so it renders on a locked-down corporate browser and has nothing to
 * exfiltrate to.
 *
 * SECURITY NOTE: the session id comes from the query string, so it is untrusted
 * input reflected onto the page. It is assigned via `textContent` ONLY, never as
 * markup, so it cannot become an element or script. Keep it that way — that single
 * assignment is what separates a static page from a reflected-XSS vector. A test
 * asserts no markup-writing sink appears anywhere in the rendered page.
 */
export function renderConsentPage(): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Linear authorized — ABCA</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 16px/1.5 ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
         margin: 0; display: grid; place-items: center; min-height: 100vh; padding: 1.5rem; }
  main { max-width: 40rem; width: 100%; }
  h1 { font-size: 1.25rem; margin: 0 0 .75rem; }
  p { margin: 0 0 .75rem; }
  code, pre { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .875rem; }
  pre { padding: .75rem; border-radius: .5rem; overflow-x: auto;
        border: 1px solid rgba(128,128,128,.35); background: rgba(128,128,128,.10); }
  .muted { opacity: .75; font-size: .875rem; }
</style>
</head>
<body>
<main>
  <h1 id="title">Finishing up…</h1>
  <p id="lede"></p>
  <pre id="session"></pre>
  <p class="muted" id="hint"></p>
  <pre id="command"></pre>
  <p class="muted">You can close this tab once the command has run.</p>
</main>
<script>
  (function () {
    var params = new URLSearchParams(window.location.search);
    var sessionId = params.get('session_id') || '';
    var title = document.getElementById('title');
    var lede = document.getElementById('lede');
    var session = document.getElementById('session');
    var hint = document.getElementById('hint');
    var command = document.getElementById('command');
    if (sessionId) {
      title.textContent = 'Linear authorized';
      lede.textContent = 'Copy this session id and paste it back into your terminal:';
      // Assigned as TEXT, never as markup — this value is untrusted query input.
      session.textContent = sessionId;
      hint.textContent = 'Then finish onboarding with:';
      command.textContent = 'bgagent linear vault-setup <workspace> --session ' + sessionId;
    } else {
      title.textContent = 'Nothing to finish here';
      lede.textContent = 'This page expects a session_id from an authorization redirect. '
        + 'Start onboarding with: bgagent linear vault-setup <workspace> --hosted';
      session.remove();
      command.remove();
    }
  })();
</script>
</body>
</html>
`;
}
