/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import * as path from 'path';
import { Duration } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Architecture, Runtime } from 'aws-cdk-lib/aws-lambda';
import * as lambda from 'aws-cdk-lib/aws-lambda-nodejs';
import { NagSuppressions } from 'cdk-nag';
import { Construct } from 'constructs';
import { OrchestrationTable } from './orchestration-table';

/**
 * Properties for RestackProcessor construct (A6, #305).
 */
export interface RestackProcessorProps {
  /** OrchestrationTable — read the DAG (branch lookup via ChildBranchIndex + snapshot). */
  readonly orchestrationTable: dynamodb.ITable;
  /** TaskTable — read a dependent's TaskRecord (its PR number) + createTaskCore writes. */
  readonly taskTable: dynamodb.ITable;
  /** Forwarded so re-stack child tasks land in the right tables. */
  readonly taskEventsTable: dynamodb.ITable;
  /** Orchestrator function ARN — createTaskCore async-invokes it. */
  readonly orchestratorFunctionArn?: string;
}

/**
 * Async-invoked processor that re-stacks stale stacked-child PRs when a
 * predecessor's PR branch changes (A6, #305). Invoked by the GitHub webhook
 * receiver on a verified ``pull_request: synchronize`` event.
 *
 * Like the OrchestrationReconciler it runs createTaskCore in-process (to
 * issue ``coding/restack-v1`` tasks), so it needs the same task-creation
 * env + grants (repo config, guardrail, orchestrator invoke, linear-oauth
 * secret). It is NOT a stream consumer — the receiver invokes it directly —
 * so no event source / DLQ here.
 */
export class RestackProcessor extends Construct {
  public readonly fn: lambda.NodejsFunction;

  constructor(scope: Construct, id: string, props: RestackProcessorProps) {
    super(scope, id);

    const handlersDir = path.join(__dirname, '..', 'handlers');

    this.fn = new lambda.NodejsFunction(this, 'RestackProcessorFn', {
      entry: path.join(handlersDir, 'orchestration-restack-processor.ts'),
      handler: 'handler',
      runtime: Runtime.NODEJS_24_X,
      architecture: Architecture.ARM_64,
      timeout: Duration.minutes(2),
      // 512 MB: bundles createTaskCore (Bedrock guardrail + attachment
      // screening SDK stack), same as the reconciler / webhook processor.
      memorySize: 512,
      environment: {
        ORCHESTRATION_TABLE_NAME: props.orchestrationTable.tableName,
        ORCHESTRATION_CHILD_BRANCH_INDEX: OrchestrationTable.CHILD_BRANCH_INDEX,
        TASK_TABLE_NAME: props.taskTable.tableName,
        TASK_EVENTS_TABLE_NAME: props.taskEventsTable.tableName,
        ...(props.orchestratorFunctionArn && {
          ORCHESTRATOR_FUNCTION_ARN: props.orchestratorFunctionArn,
        }),
      },
      bundling: {
        externalModules: ['@aws-sdk/*'],
      },
    });

    // Read the DAG (branch GSI + snapshot); read/write TaskTable
    // (PR-number read + createTaskCore); write task events.
    props.orchestrationTable.grantReadData(this.fn);
    props.taskTable.grantReadWriteData(this.fn);
    props.taskEventsTable.grantReadWriteData(this.fn);

    NagSuppressions.addResourceSuppressions(this.fn, [
      {
        id: 'AwsSolutions-IAM4',
        reason: 'AWSLambdaBasicExecutionRole is required for CloudWatch Logs access',
      },
      {
        id: 'AwsSolutions-IAM5',
        reason:
          'DynamoDB index/* wildcard generated by CDK grantReadData for the ChildBranchIndex query',
      },
    ], true);
  }
}
