/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * Properties for SlackUserMappingTable construct.
 */
export interface SlackUserMappingTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table mapping Slack user IDs to Cognito subs for
 * Slack-button approvals (design §11.2, finding #4).
 *
 * Schema: `slack_user_id` (PK). One row per Slack identity; the sole
 * non-key attribute is `cognito_sub`. No GSI is provided for the
 * reverse direction (Cognito → Slack) because that lookup is not
 * trust-sensitive and can be derived offline if ever needed.
 *
 * Writes are gated through the `LinkSlackUserFn` Lambda (Chunk 5)
 * which requires BOTH a valid Cognito ID token AND a Slack OAuth
 * token for the user being mapped. Admins do not have a bulk-write
 * API, and the `ConditionExpression: attribute_not_exists(slack_user_id)`
 * on that Put prevents a subsequent Slack-admin compromise from
 * overwriting an existing mapping.
 *
 * NOT provided as part of this construct:
 *
 * - Stream (no consumer needs row-change events; every write is a
 *   user-initiated link, audit lives on CloudTrail + the handler's
 *   explicit audit event on TaskEventsTable).
 * - Reverse GSI (Cognito → Slack) — would widen the trust surface
 *   without adding capability we need in v1.
 */
export class SlackUserMappingTable extends Construct {
  /**
   * The underlying DynamoDB table. Use this to grant access or read
   * the table name.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: SlackUserMappingTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'slack_user_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });
  }
}
