/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * GSI name for the `user_id-status-index`. Exported so handlers that
 * issue Query calls against the GSI reference the same identifier the
 * table was built with — renaming the GSI would break `bgagent pending`
 * without a loud failure.
 */
export const USER_STATUS_INDEX_NAME = 'user_id-status-index';

/**
 * Properties for TaskApprovalsTable construct.
 */
export interface TaskApprovalsTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table. The design (§10.1) recommends RETAIN
   * in production to preserve the audit trail; we default to DESTROY to
   * match the rest of the sample and keep teardowns cheap. Override per
   * environment.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table for Cedar-HITL approval gates (design §10.1).
 *
 * Schema: `task_id` (PK, ULID matching TaskTable) + `request_id` (SK,
 * ULID minted by the agent). Each row represents one human-in-the-loop
 * approval gate. The trusted approval request service creates PENDING rows;
 * owner-authenticated decision handlers record APPROVED / DENIED. Task closure
 * cancels unanswered requests. Workers have no direct approval-row write grant.
 *
 * A GSI (`user_id-status-index`) supports the `bgagent pending` access
 * pattern — `user_id = :caller AND status = :pending` — without
 * requiring a full-table Scan. The GSI ships in v1 because under
 * `watch -n1`-style polling the Scan alternative would exhaust DDB
 * burst capacity per-user (§10.1 finding #8).
 *
 * Streams are intentionally OFF (§11.2). TaskApprovalsTable is working
 * state; the audit trail lives on TaskEventsTable which already has
 * streams wired into the fan-out Lambda. Enabling streams here would
 * create duplicate fan-out paths.
 *
 * Pending rows have no TTL, including requests with an explicit deadline.
 * Task closure applies retention cleanup; capacity delays must never erase
 * the recorded decision before a replacement worker consumes it.
 */
export class TaskApprovalsTable extends Construct {
  /**
   * The underlying DynamoDB table. Use this to grant access or read the
   * table name.
   */
  public readonly table: dynamodb.Table;

  /**
   * Name of the `user_id-status-index` GSI — callers that Query the GSI
   * should read this rather than hard-coding the string.
   */
  public readonly userStatusIndexName: string = USER_STATUS_INDEX_NAME;

  constructor(scope: Construct, id: string, props: TaskApprovalsTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'task_id',
        type: dynamodb.AttributeType.STRING,
      },
      sortKey: {
        name: 'request_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: 'ttl',
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      // NO DynamoDB stream — §11.2. TaskEventsTable is the audit fan-out
      // path; this table holds working state only.
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });

    // GSI for GET /v1/pending — user_id PK + status SK (§10.1).
    //
    // Preserve the existing INCLUDE projection. The pending-list endpoint uses
    // this GSI to discover candidates, then strongly reads approval/task rows
    // before returning them; GSI results alone may contain stale decisions.
    this.table.addGlobalSecondaryIndex({
      indexName: USER_STATUS_INDEX_NAME,
      partitionKey: {
        name: 'user_id',
        type: dynamodb.AttributeType.STRING,
      },
      sortKey: {
        name: 'status',
        type: dynamodb.AttributeType.STRING,
      },
      projectionType: dynamodb.ProjectionType.INCLUDE,
      nonKeyAttributes: [
        'task_id',
        'request_id',
        'tool_name',
        'tool_input_preview',
        'severity',
        'reason',
        'created_at',
        'timeout_s',
        // DynamoDB rejects in-place projection changes. New response fields
        // can come from the existing base-table read without changing this GSI.
        'matching_rule_ids',
      ],
    });
  }
}
