/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';

/**
 * Properties for TaskTable construct.
 */
export interface TaskTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table for persisting task state across the agent lifecycle.
 *
 * Schema: task_id (PK) with three GSIs for querying by user+status,
 * by status (queue processing), and by idempotency key (dedup).
 *
 * GSIs:
 * - UserStatusIndex (PK: user_id, SK: status_created_at) — "my tasks" queries
 * - StatusIndex (PK: status, SK: created_at) — queue processing, monitoring
 * - IdempotencyIndex (PK: idempotency_key) — sparse index for dedup
 */
export class TaskTable extends Construct {
  /**
   * GSI name for querying tasks by user and status.
   * PK: user_id, SK: status_created_at (composite: `{status}#{created_at}`).
   */
  public static readonly USER_STATUS_INDEX = 'UserStatusIndex';

  /**
   * GSI name for querying tasks by status.
   * PK: status, SK: created_at.
   */
  public static readonly STATUS_INDEX = 'StatusIndex';

  /**
   * GSI name for idempotency dedup.
   * PK: idempotency_key. Sparse index — only items with the key are projected.
   */
  public static readonly IDEMPOTENCY_INDEX = 'IdempotencyIndex';

  /**
   * The underlying DynamoDB table. Use this to grant access or read the table name.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: TaskTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'task_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: 'ttl',
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });

    // GSI: query tasks by user, optionally filtered by status
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.USER_STATUS_INDEX,
      partitionKey: { name: 'user_id', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'status_created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.ALL,
    });

    // GSI: query tasks by status (for queue processing, monitoring)
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.STATUS_INDEX,
      partitionKey: { name: 'status', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.ALL,
    });

    // GSI: idempotency dedup (sparse — only items with idempotency_key)
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.IDEMPOTENCY_INDEX,
      partitionKey: { name: 'idempotency_key', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.KEYS_ONLY,
    });
  }
}
